CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" varchar(20) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "classes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "mentor_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "class_members" (
  "class_id" bigint NOT NULL,
  "member_id" bigint NOT NULL,
  "joined_at" timestamp NOT NULL,
  PRIMARY KEY ("class_id", "member_id")
);

CREATE TABLE "lessons" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" bigint NOT NULL,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "lesson_order" int NOT NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "lesson_progress" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint NOT NULL,
  "member_id" bigint NOT NULL,
  "completed_at" timestamp NOT NULL
);

CREATE TABLE "assignments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" bigint NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "deadline" timestamp NOT NULL,
  "maximum_score" decimal(5,2) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "submissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignment_id" bigint NOT NULL,
  "member_id" bigint NOT NULL,
  "content" text,
  "repository_url" varchar(500),
  "submitted_at" timestamp NOT NULL,
  "score" decimal(5,2),
  "feedback" text,
  "reviewed_at" timestamp
);

CREATE INDEX ON "classes" ("mentor_id");

CREATE INDEX ON "class_members" ("member_id");

CREATE INDEX ON "lessons" ("class_id");

CREATE INDEX ON "lessons" ("created_by");

CREATE UNIQUE INDEX ON "lesson_progress" ("lesson_id", "member_id");

CREATE INDEX ON "lesson_progress" ("member_id");

CREATE INDEX ON "assignments" ("class_id");

CREATE INDEX ON "submissions" ("assignment_id");

CREATE INDEX ON "submissions" ("member_id");

COMMENT ON COLUMN "users"."role" IS 'ADMIN or MEMBER';

ALTER TABLE "classes" ADD FOREIGN KEY ("mentor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_members" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_members" ADD FOREIGN KEY ("member_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_progress" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_progress" ADD FOREIGN KEY ("member_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assignments" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submissions" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submissions" ADD FOREIGN KEY ("member_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
